### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by LoveqLRC** [senlinxuefeng/RSQMonthCalendar#3]
```
  Process: com.yumingchuan.rsqmonthcalendar, PID: 26635
                                                   java.lang.IndexOutOfBoundsException: Invalid index 4, size is 2
                                                       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                       at java.util.ArrayList.set(ArrayList.java:481)
                                                       at android.support.v4.app.FragmentManagerImpl.makeInactive(FragmentManager.java:1662)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1452)
                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:753)
                                                       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                       at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1984)
                                                       at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
                                                       at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:166)
                                                       at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
                                                       at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:668)
                                                       at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:630)
                                                       at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:611)
                                                       at com.yumingchuan.rsqmonthcalendar.ui.MonthViewFragment.setWeekFragmentData(MonthViewFragment.java:846)
                                                       at com.yumingchuan.rsqmonthcalendar.ui.MonthViewFragment.access$000(MonthViewFragment.java:48)
                                                       at com.yumingchuan.rsqmonthcalendar.ui.MonthViewFragment$1.handleMessage(MonthViewFragment.java:58)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5671)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by senlinxuefeng** [comment]
恩恩，我好查查代码
